# -----------------------
# 网站基本设置
# -----------------------
title: "Yuhang Bai"
url: "https://Yuhang-Bai.github.io" # 记得改成您的 GitHub 用户名
minimal_mistakes_skin: "default"      # 主题配色

# -----------------------
# 关键：作者侧边栏信息
# -----------------------
author:
  name: "Yuhang Bai"
  avatar: "/images/profile.png"       # ❗请确保在仓库 images 文件夹下放入您的照片 profile.jpg
  bio: "PhD Candidate at **NWPU**"
  location: "Xi'an, China"
  email: "yuhang.bai66@gmail.com"
  links:
    - label: "Google Scholar"
      icon: "fas fa-graduation-cap"
      url: "https://scholar.google.com.hk/citations?user=rznH-g4AAAAJ&hl=zh-CN" # 填入链接

# -----------------------
# 开启数学公式 (MathJax)
# -----------------------
head_scripts:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: true

