# -----------------------
# Site Settings
# -----------------------
title: "Yuhang Bai"
author:
  name: "Yuhang Bai"
  avatar: "/images/profile.png" # 请确保在 files/images 文件夹下有一张名为 profile.png 的照片
  bio: "PhD Candidate at NWPU"
  location: "Xi'an, China"
  email: "yuhang.bai66@gmail.com"
  googlescholar: "" # 如果有，填入 ID，没有则留空
  github: "Yuhang-Bai"  # 填入你的 GitHub 用户名
  researchgate: ""
  linkedin: ""

# -----------------------
# Theme Settings
# -----------------------
minimal_mistakes_skin: "default" # 保持默认，或者选 "air", "sunrise"
locale: "en-US"
url: "https://Yuhang-Bai.github.io" # 修改为你的实际网址
baseurl: "" # 如果是主站，留空

# -----------------------
# Navigation
# -----------------------
# 保持 academicpages 默认的导航栏设置即可，或者根据需要精简

